image: node:20

stages:
  - install
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - Frontend/node_modules/

before_script:
  - cd Frontend

install_dependencies:
  stage: install
  script:
    - npm install --save d3-contour d3-delaunay mesh-slice-polygon point-in-polygon polygon-clipping
  artifacts:
    paths:
      - Frontend/node_modules/
build_frontend:
  stage: build
  script:
    - npm run build
    - echo "Compiling the code..."
    - echo "Compile complete."
  artifacts:
    paths:
      - Frontend/dist/